"""Export command."""

from __future__ import annotations

import traceback
from pathlib import Path

import click

from envio import __version__
from envio.cli_helpers import (
    _find_environment,
    _get_console,
    _is_writable,
    _load_dotenv,
)


def _generate_requirements_export(packages: list[dict], version: str) -> str:
    """Generate requirements.txt content."""
    lines = [f"# Generated by envio {version}\n"]
    for pkg in sorted(packages, key=lambda x: x["name"].lower()):
        lines.append(f"{pkg['name']}=={pkg['version']}\n")
    return "".join(lines)


def _generate_dockerfile_export(
    packages: list[dict], python_version: str, version: str
) -> str:
    """Generate Dockerfile content."""
    major_minor = ".".join(python_version.split(".")[:2])
    pkg_list = " ".join(
        f"{pkg['name']}=={pkg['version']}"
        for pkg in sorted(packages, key=lambda x: x["name"].lower())
    )

    return f"""# Generated by envio {version}
FROM python:{major_minor}-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir {pkg_list}

# Copy application code
COPY . .

CMD ["python"]
"""


def _generate_devcontainer_export(
    packages: list[dict],
    python_version: str,
    env_name: str,
    version: str,
) -> str:
    """Generate devcontainer.json content."""
    import json

    pkg_list = " ".join(
        f"{pkg['name']}=={pkg['version']}"
        for pkg in sorted(packages, key=lambda x: x["name"].lower())
    )

    devcontainer = {
        "name": env_name,
        "image": f"mcr.microsoft.com/devcontainers/python:{'.'.join(python_version.split('.')[:2])}",
        "postCreateCommand": f"pip install {pkg_list}",
        "customizations": {
            "vscode": {
                "extensions": [
                    "ms-python.python",
                    "ms-python.vscode-pylance",
                ],
                "settings": {
                    "python.defaultInterpreterPath": "/usr/local/bin/python",
                },
            }
        },
    }

    return json.dumps(devcontainer, indent=2) + "\n"


@click.command()
@click.option("--name", "-n", default=None, help="Environment name")
@click.option("--path", "-p", default=None, help="Environment path")
@click.option("--output", "-o", default=None, help="Output file path")
@click.option(
    "--format",
    "fmt",
    default="requirements",
    type=click.Choice(["requirements", "dockerfile", "devcontainer"]),
    help="Export format",
)
@click.option("--verbose", "-v", is_flag=True, help="Enable verbose output")
def export(
    name: str | None,
    path: str | None,
    output: str | None,
    fmt: str,
    verbose: bool,
) -> None:
    """Export environment configuration to various formats.

    \b
    Examples:
        envio export -n my-env --format requirements
        envio export -n my-env --format dockerfile
        envio export -n my-env --format devcontainer
    """
    _load_dotenv()
    console = _get_console(verbose)
    console.print_header("Envio Export", f"Export to {fmt} format")

    try:
        import platform

        from envio.core.virtualenv_manager import VirtualEnvManager

        manager = VirtualEnvManager()

        # Find environment using shared helper
        env_path = _find_environment(name, path, console)
        if not env_path:
            return

        console.print_info(f"Exporting environment: {env_path}")

        # Get installed packages with versions
        success, packages = manager.get_installed_packages_with_versions(env_path)

        if not success:
            console.print_error("Failed to get installed packages")
            return

        if not packages:
            console.print_warning("No packages installed in this environment")
            return

        python_version = platform.python_version()
        env_name = name or env_path.name

        # Generate content based on format
        if fmt == "requirements":
            content = _generate_requirements_export(packages, __version__)
            default_output = "requirements.txt"
        elif fmt == "dockerfile":
            content = _generate_dockerfile_export(packages, python_version, __version__)
            default_output = "Dockerfile"
        elif fmt == "devcontainer":
            content = _generate_devcontainer_export(
                packages, python_version, env_name, __version__
            )
            default_output = "devcontainer.json"
        else:
            console.print_error(f"Unknown format: {fmt}")
            return

        # Determine output file
        output_path = Path(output) if output else Path(default_output)

        if output_path.exists():
            console.print_warning(f"{output_path} already exists.")
            if not console.confirm("Overwrite?", default=False):
                console.print_warning("Aborted. No file was exported.")
                return

        if not _is_writable(output_path):
            console.print_error(f"Cannot write to {output_path}. Check permissions.")
            return

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

        console.print_success(f"Exported to: {output_path}")
        console.print_info(f"Format: {fmt}")
        console.print_info(f"Packages: {len(packages)}")

    except Exception as e:
        console.print_error(f"Error: {e}")
        if verbose:
            console._safe_print(traceback.format_exc())
