"""Lockfile pinning for supply chain security.

After a scan, ``pin_versions`` writes a security-focused lockfile that pins
every installed package to its exact version.  The lockfile is separate from
a general-purpose ``requirements.lock`` so it is clear it was generated by a
security scan rather than the normal sync workflow.

File written: ``envio-security.lock`` (plain text, one ``name==version`` per
line).  A JSON variant (``envio-security.lock.json``) is also emitted when
``json_output=True``, containing the full scan metadata alongside the pins.

Format of the plain-text lockfile
----------------------------------
::

    # envio security lockfile
    # generated: 2026-04-07T12:34:56+00:00
    # environment: /path/to/.venv
    # packages: 42  safe: 39  flagged: 3
    #
    # FLAGGED packages are marked with a comment. Review before deploying.
    #
    requests==2.31.0       # SAFE
    reqeusts==1.0.0        # FLAGGED risk=72 typo-of=requests
    ...

"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from envio.supplychain.scanner import ScanResult


@dataclass
class PinResult:
    """Result of a pin_versions call."""

    lockfile_path: Path
    json_path: Path | None
    total_packages: int
    flagged_packages: int
    safe_packages: int
    pins: list[str] = field(default_factory=list)  # "name==version" strings


def pin_versions(
    scan_result: ScanResult,
    env_path: str | Path,
    output_dir: str | Path | None = None,
    json_output: bool = False,
) -> PinResult:
    """Write a security-focused lockfile that pins all scanned packages.

    Parameters
    ----------
    scan_result:
        The ``ScanResult`` returned by ``scan_packages()``.
    env_path:
        Path to the environment that was scanned (used as metadata only).
    output_dir:
        Directory where ``envio-security.lock`` is written.  Defaults to the
        current working directory.
    json_output:
        When ``True``, also write ``envio-security.lock.json`` with full
        scan metadata.

    Returns
    -------
    PinResult
        Paths and summary counts for the generated file(s).
    """
    output_dir = Path(output_dir) if output_dir else Path.cwd()
    output_dir.mkdir(parents=True, exist_ok=True)

    lockfile_path = output_dir / "envio-security.lock"
    json_path = (output_dir / "envio-security.lock.json") if json_output else None

    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    total = len(scan_result.packages)
    flagged = [p for p in scan_result.packages if p.risk_score >= 15]
    safe = [p for p in scan_result.packages if p.risk_score < 15]
    pins: list[str] = []

    lines: list[str] = [
        "# envio security lockfile",
        f"# generated: {now}",
        f"# environment: {env_path}",
        f"# packages: {total}  safe: {len(safe)}  flagged: {len(flagged)}",
        "#",
        "# FLAGGED packages are marked with a comment. Review before deploying.",
        "#",
    ]

    for pkg in scan_result.packages:
        pin = f"{pkg.package}=={pkg.version}" if pkg.version else pkg.package
        pins.append(pin)

        if pkg.risk_score >= 90:
            level = "CRITICAL"
        elif pkg.risk_score >= 70:
            level = "FLAGGED-HIGH"
        elif pkg.risk_score >= 40:
            level = "FLAGGED-MEDIUM"
        elif pkg.risk_score >= 15:
            level = "FLAGGED-LOW"
        else:
            level = "SAFE"

        comment = f"# {level}"
        if pkg.risk_score >= 15 and pkg.flags:
            # Condense the first flag into a short hint (≤60 chars)
            hint = pkg.flags[0][:60].replace("\n", " ")
            comment += f" | {hint}"

        lines.append(f"{pin:<45} {comment}")

    lockfile_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Optional JSON output
    if json_output and json_path is not None:
        payload: dict[str, Any] = {
            "generated": now,
            "environment": str(env_path),
            "summary": {
                "total": total,
                "safe": len(safe),
                "flagged": len(flagged),
                "critical": scan_result.critical_count,
                "high": scan_result.high_count,
                "medium": scan_result.medium_count,
                "low": scan_result.low_count,
            },
            "packages": [
                {
                    "name": p.package,
                    "version": p.version,
                    "pin": f"{p.package}=={p.version}" if p.version else p.package,
                    "risk_score": p.risk_score,
                    "flags": p.flags,
                    "suggestions": p.suggestions,
                }
                for p in scan_result.packages
            ],
        }
        json_path.write_text(
            json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8"
        )

    return PinResult(
        lockfile_path=lockfile_path,
        json_path=json_path,
        total_packages=total,
        flagged_packages=len(flagged),
        safe_packages=len(safe),
        pins=pins,
    )


def verify_lockfile(
    lockfile_path: str | Path,
    current_packages: list[str],
) -> tuple[list[str], list[str], list[str]]:
    """Compare installed packages against a previously written security lockfile.

    Returns three lists:
        - ``matched``: packages whose pin matches exactly
        - ``mismatched``: packages present but at a different version
        - ``missing``: pins in the lockfile not found in current packages
    """
    lockfile_path = Path(lockfile_path)
    if not lockfile_path.exists():
        raise FileNotFoundError(f"Lockfile not found: {lockfile_path}")

    pinned: dict[str, str] = {}
    for raw_line in lockfile_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        # Strip inline comments ("name==version  # SAFE ...")
        pin_part = line.split("#")[0].strip()
        if "==" in pin_part:
            name, version = pin_part.split("==", 1)
            pinned[name.strip().lower()] = version.strip()
        else:
            pinned[pin_part.lower()] = ""

    current: dict[str, str] = {}
    for spec in current_packages:
        if "==" in spec:
            name, version = spec.split("==", 1)
            current[name.strip().lower()] = version.strip()
        else:
            current[spec.strip().lower()] = ""

    matched: list[str] = []
    mismatched: list[str] = []
    missing: list[str] = []

    for name, pinned_ver in pinned.items():
        if name not in current:
            missing.append(f"{name}=={pinned_ver}" if pinned_ver else name)
        elif current[name] != pinned_ver:
            mismatched.append(
                f"{name}: pinned={pinned_ver or '?'} installed={current[name] or '?'}"
            )
        else:
            matched.append(f"{name}=={pinned_ver}" if pinned_ver else name)

    return matched, mismatched, missing
